language: node_js

node_js:
  - '8'

cache:
  yarn: true
  bundler: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn run bootstrap

script: yarn run test

sudo: false
